#!/bin/bash

# Script para inicialização do uso do Fluxbox.

# Última atualização: 17-03-2025.

setxkbmap -model abnt2 -layout br

# fbsetbg /home/antoniovandre/Imagens/Wallpapers/AV3DNavigator\ -\ Wallpaper\ -\ Trombeta\ de\ Gabriel.png
