#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script de escrita com delay. Para Puppy Linux.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 08-08-2021.

SOM="0"
ARQUIVOSOM="/usr/local/share/antoniovandre_echo_tick.wav"
DELAY="0"

VAR="${1}"
TAMANHO=${#VAR}
CONTADOR="0"

if [ "${SOM}" == "1" ]; then if ! hash play &>> /dev/null; then echo "Não encontrado o software \"play\"."; exit 1; fi; fi

while [ $CONTADOR -lt $TAMANHO ]; do CHAR=${VAR:$CONTADOR:1}; if [ -z $CHAR ]; then echo -n " "; else GLOBIGNORE="*" echo -n "${CHAR}"; fi; if [ $SOM == "1" ]; then play $ARQUIVOSOM &>> /dev/null; fi; sleep ${DELAY}s; CONTADOR=$(expr $CONTADOR + 1); done

if [ -z "${2}" ]; then echo ""; else if ! [ "${2}" == "n" ]; then echo ""; fi; fi
