#!/bin/sh

# Script de limitação do uso da cpu pelo Firefox, na GUI. De Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).

xterm antoniovandre_cpulimit_firefox

