#!/bin/sh

# Script de pausa do daemon "dropbox". De Antonio Vandré Pedrosa Furtunato Gomes (http://bit.ly/antoniovandre_legadoontologico).

# Última atualização: 09-03-2016.

dropbox stop

sleep 3s

