#!/bin/bash

# Simples script de caixa de diálogo.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 03-09-2025. Não considerando alterações em variáveis globais.

if [ "${#}" -lt "2" ]; then echo "Requer no mínimo 2 argumentos."; exit 1; fi

if [ "${1}" == "python" ]; then
	if ! hash python3 &>> /dev/null; then echo "Python 3 não encontrado."; exit 1; fi

	if ! ls "${HOME}/software_sources/Python/Aviso.py" &>> /dev/null; then echo "Script Python não encontrado."; exit 1; fi

	python3 "${HOME}/software_sources/Python/Aviso.py" "${2}"
else if [ "${1}" == "gtk" ]; then
	if ! ls "${HOME}/software_sources/C/aviso" &>> /dev/null; then echo "Software GTK não encontrado."; exit 1; fi

	"${HOME}/software_sources/C/aviso" "${2}" "${3}"
else if [ "${1}" == "console" ]; then
	if ! ls "${HOME}/shell_scripts/Utilitários/antoniovandre_dialogbox" &>> /dev/null; then echo "Software console não encontrado."; exit 1; fi

	"${HOME}/shell_scripts/Utilitários/antoniovandre_dialogbox" "${2}"
fi; fi; fi
