#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script de backup de antoniovandre-frases.txt.

# Última atualização: 22-03-2020.

DIRETORIOAVBASHSCRIPTS="${HOME}/shell_scripts/Ubuntu/"

ARQUIVOFRASES="/usr/local/share/antoniovandre-frases.txt"
AVDOCDB="/Documents/BACKUPED14/"

FLAG="0"

if ! hash antoniovandre_echo 1>> /dev/null 2>> /dev/null; then echo "antoniovandre_echo não encontrado."; read; FLAG="1"; fi

if [ "${FLAG}" == "0" ]; then if ! [ -n "$AVCORES" ]; then if ! source "${DIRETORIOAVBASHSCRIPTS}antoniovandre_cores"; then echo "Ocorreu um erro ao carregar o arquivo de cores."; fi; fi; fi

if [ "${FLAG}" == "0" ]; then antoniovandre_echo "Copiando para documentos local... " n; if cp "${ARQUIVOFRASES}" "${HOME}/Documentos/" 1>> /dev/null 2>> /dev/null; then echo -e "${AV_VERDE}OK${AV_SEMCOR}."; else echo -n "${AV_VERMELHO}Falhou${AV_SEMCOR}."; FLAG="1"; fi; fi

if [ "${FLAG}" == "0" ]; then antoniovandre_echo "Copiando para o diretório de documentos no Dropbox... " n; if antoniovandre_dbxcli_put "${ARQUIVOFRASES}" "${AVDOCDB}${ARQUIVOFRASES##*/}" 1>> /dev/null 2>> /dev/null; then echo -e "${AV_VERDE}OK${AV_SEMCOR}."; else echo -n "${AV_VERMELHO}Falhou${AV_SEMCOR}."; FLAG="1"; fi; fi

echo ""

if [ "${FLAG}" == "0" ]; then echo -e "${AV_VERDE}Sucesso${AV_SEMCOR}."; else echo -e "${AV_VERMELHO}Ocorreu um erro${AV_SEMCOR}."; fi

if ! [ -z $1 ]; then if [ $1 == "prompt" ]; then echo ""; antoniovandre_echo "Pressione RETURN para sair."; read; fi; fi

