#!/bin/bash

# Script de inicialização do navegador Google Chromium, por Antonio Vandré Pedrosa Furtunato Gomes.

# Última atualização: 29-11-2020.

if [ "${1}" == "l" ]; then cpulimit -l 1 -- chromium-browser --disable-hang-monitor &>> /dev/null; else chromium-browser --disable-hang-monitor &>> /dev/null; fi
