#!/bin/bash

# Script de verificação de conexão com a internet. De Antonio Vandré Pedrosa Furtunato Gomes. Para Ubuntu.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 05-08-2021.

URLFILE="/usr/local/share/antoniovandre_urltouch.txt"

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "antoniovandre_cores" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! ls "${URLFILE}" &>> /dev/null; then echo -e "${AV_VERMELHO}Arquivo de URL não encontrado${AV_SEMCOR}."; exit 1; else URLTOUCH=$(cat "${URLFILE}" | tr -d "\n"); fi

if ! hash traceroute &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"traceroute\" não encontrado${AV_SEMCOR}."; exit 1; fi

while ! traceroute "${URLTOUCH}" >> /dev/null 2>> /dev/null; do echo -ne "${AV_VERMELHO}Ainda sem internet${AV_SEMCOR}... Crtl+C para sair. "; date; sleep 3s; done

echo -e "${AV_VERDE}Internet acessível${AV_SEMCOR}."

