#!/bin/bash

# Simples script de visualização de textos. De Antonio Vandré Pedrosa Furtunato Gomes.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 11-07-2020.

if ! hash xterm &>> /dev/null; then echo -e "Software \"xterm\" não encontrado."; exit 1; fi

if ! ls "${1}" &>> /dev/null; then echo -e "Arquivo não encontrado."; exit 1; fi

cat "${1}"

echo -e "\nPressione RETURN para sair."; read

