#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script de aliases. Deve ser executado com "source".

# Última atualização: 03-09-2025.

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/shell_scripts/Utilitários/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "${BASHSCRIPTS}antoniovandre_cores" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if [ "${1}" == "0" ]; then

echo -ne "Removendo aliases... "

unalias apbk
unalias albk
unalias crpt
unalias aprbk
unalias av3dswbk
unalias av3dscbk
unalias avbrbk
unalias mrqbk
unalias tmega
unalas mrck
unalias avkill
unalias av3dst
unalias f
unalias rn
unalias rd
unalias cst
unalias dl
unalias dl1s
unalias sd
unalias sp
unalias rb
unalias sa
unalias ra
unalias lp
unalias vi
unalias db
unalias rss
unalias uol
unalias scdly
unalias folha
unalias sat1
unalias sat15
unalias sat2
unalias sat4
unalias br0
unalias br10
unalias br20
unalias gm06
unalias gm1
unalias gm15
unalias xcz
unalias ap
unalias ag
unalias ac
unalias c

# Início aliases matemáticos 1/1.

unalias S
unalias P
unalias Im
unalias Se
unalias Co
unalias Ta
unalias Ct
unalias Sc
unalias Cs
unalias As
unalias Ac
unalias At
unalias Act
unalias Asc
unalias Acs
unalias Pt
unalias Rts
unalias Vnp
unalias Ev
unalias Evn
unalias Der
unalias Int
unalias Fmp
unalias Rz
unalias Nr
unalias Dt

unalias Pts

unalias Ce

unalias Re

unalias Gp

unalias Comp

unalias Grs

unalias Evg

unalias Gf

unalias Gr

unalias Grp

unalias Grpol

unalias Grppol

unalias Gr3

unalias Gr3sp

unalias Gr3spol

unalias Gr3ct

# Fim aliases matemáticos 1/1.

# Início aliases temporários 1/1.

unalias aliastemp

# Fim aliases temporários 1/1.

else

echo -ne "Carregando aliases... "

alias apbk="antoniovandre_backupanotacoespublicas"
alias crpt="antoniovandre_cripto"
alias aprbk="antoniovandre_backupanotacoesprivadas"
alias albk="antoniovandre_backupartigoslidos"
alias av3dswbk="antoniovandre_backupav3dspacewar"
alias av3dscbk="antoniovandre_backupav3dspacecatch"
alias avbrbk="antoniovandre_backupavblockrun"
alias mrqbk="antoniovandre_backupmrquizdata"
alias tmega="antoniovandre_touchmega"
alias mrck=". ${HOME}/shell_scripts/Mathematical\ Ramblings/antoniovandre_mathematicalramblings_check"
alias avkill="antoniovandre_kill"
alias av3dst="antoniovandre_av3dnavigator_estatisticas"
alias f="antoniovandre_frases_aleatorias"
alias rn="antoniovandre_background redshift -O 5000k"
alias rd="antoniovandre_background redshift -O 6500k"
alias cst="antoniovandre_cpususpendtemperature"
alias dl="antoniovandre_daylight"
alias dl1s="antoniovandre_daylight_1s"
alias sd="sudo shutdown -h now"
alias sp="sudo pm-suspend"
alias rb="sudo reboot"
alias sa="antoniovandre_showaliases"
alias ra="source antoniovandre_aliases 0"
alias lp="nice -n 20 antoniovandre_logprocessos"
alias vi="antoniovandre_verificarinternet"
alias db="antoniovandre_dropboxsync"
alias rss="nice -n 20 antoniovandre_leitorrss"
alias uol="nice -n 20 antoniovandre_leitorrss http://rss.uol.com.br/feed/noticias.xml 120"
alias scdly="nice -n 20 antoniovandre_leitorrss https://www.sciencedaily.com/rss/all.xml 120"
alias folha="nice -n 20 antoniovandre_leitorrss https://feeds.folha.uol.com.br/emcimadahora/rss091.xml 120"
alias sat1="if hash '${HOME}/libvibrant-1.1.1/build/cli/vibrant-cli' &>> /dev/null; then '${HOME}/libvibrant-1.1.1/build/cli/vibrant-cli' $(xrandr | grep ' connected' | cut -d ' ' -f 1) 1; fi"
alias sat15="if hash '${HOME}/libvibrant-1.1.1/build/cli/vibrant-cli' &>> /dev/null; then '${HOME}/libvibrant-1.1.1/build/cli/vibrant-cli' $(xrandr | grep ' connected' | cut -d ' ' -f 1) 1.5; fi"
alias sat2="if hash '${HOME}/libvibrant-1.1.1/build/cli/vibrant-cli' &>> /dev/null; then '${HOME}/libvibrant-1.1.1/build/cli/vibrant-cli' $(xrandr | grep ' connected' | cut -d ' ' -f 1) 2; fi"
alias sat4="if hash '${HOME}/libvibrant-1.1.1/build/cli/vibrant-cli' &>> /dev/null; then '${HOME}/libvibrant-1.1.1/build/cli/vibrant-cli' $(xrandr | grep ' connected' | cut -d ' ' -f 1) 4; fi"
alias br0="if hash xcalib &>> /dev/null; then if [ '$(ps -A | grep Xorg)' != '' ]; then xcalib -b 0 -a &>> /dev/null; fi; fi"
alias br10="if hash xcalib &>> /dev/null; then if [ '$(ps -A | grep Xorg)' != '' ]; then xcalib -b 10 -a &>> /dev/null; fi; fi"
alias br20="if hash xcalib &>> /dev/null; then if [ '$(ps -A | grep Xorg)' != '' ]; then xcalib -b 20 -a &>> /dev/null; fi; fi"
alias gm06="if hash xcalib &>> /dev/null; then if [ '$(ps -A | grep Xorg)' != '' ]; then xcalib -gc 0.6 -a &>> /dev/null; fi; fi"
alias gm1="if hash xcalib &>> /dev/null; then if [ '$(ps -A | grep Xorg)' != '' ]; then xcalib -gc 1 -a &>> /dev/null; fi; fi"
alias gm15="if hash xcalib &>> /dev/null; then if [ '$(ps -A | grep Xorg)' != '' ]; then xcalib -gc 1.5 -a &>> /dev/null; fi; fi"
alias xcz="if hash xcalib &>> /dev/null; then if [ '$(ps -A | grep Xorg)' != '' ]; then xcalib -c &>> /dev/null; fi; fi"
alias ap="antoniovandre_aviso python"
alias ag="antoniovandre_aviso gtk"
alias ac="antoniovandre_aviso console"
alias c="antoniovandre_cmd"

# Início aliases matemáticos 1/1.

alias S="antoniovandre_soma"
alias P="antoniovandre_produto"
alias Im="antoniovandre_inversomultiplicativo"
alias Se="antoniovandre_seno"
alias Co="antoniovandre_cosseno"
alias Ta="antoniovandre_tangente"
alias Ct="antoniovandre_cotangente"
alias Sc="antoniovandre_secante"
alias Cs="antoniovandre_cossecante"
alias As="antoniovandre_arcoseno"
alias Ac="antoniovandre_arcocosseno"
alias At="antoniovandre_arcotangente"
alias Act="antoniovandre_arcocotangente"
alias Asc="antoniovandre_arcosecante"
alias Acs="antoniovandre_arcocossecante"
alias Pt="antoniovandre_potencia"
alias Rts="antoniovandre_reduzirtermossemelhantes"
alias Vnp="antoniovandre_valornumericopolinomio"
alias Ev="antoniovandre_eval"
alias Evn="antoniovandre_eval_nolog"
alias Der="antoniovandre_derivada"
alias Int="antoniovandre_integraldefinida"
alias Fmp="antoniovandre_funcaomaisproxima /home/antoniovandre/software_sources/C/Math/antoniovandre_pontos.txt /home/antoniovandre/software_sources/C/Math/antoniovandre_funcoes.txt 1"
alias Pc="antoniovandre_produtocomplexos"
alias Rz="antoniovandre_raizesfuncao"
alias Nr="antoniovandre_numeroraizes"
alias Dt="antoniovandre_determinante"

alias Pts="antoniovandre_proximotermosequencia"

alias Ce="if ls /home/antoniovandre/software_sources/C/Math/antoniovandre_math_estatisticas.txt &>> /dev/null; then cat /home/antoniovandre/software_sources/C/Math/antoniovandre_math_estatisticas.txt; else echo \"Arquivo de estatísticas matemáticas ainda não existente.\"; fi"

alias Re="rm /home/antoniovandre/software_sources/C/Math/antoniovandre_math_estatisticas.txt &>> /dev/null; rm /home/antoniovandre/software_sources/C/Math/antoniovandre_math_estatisticas.png &>> /dev/null"

alias Gp="antoniovandre_gnuplot_mathstatistics"

alias Comp="antoniovandre_cmath_compilar"

alias Grs="if ls /home/antoniovandre/software_sources/C/Math/antoniovandre_math_estatisticas.png &>> /dev/null; then eog /home/antoniovandre/software_sources/C/Math/antoniovandre_math_estatisticas.png &>> /dev/null; else echo 'Arquivo imagem gráfico não encontrado.'; fi"

alias Evg="python3 /home/antoniovandre/software_sources/Python/antoniovandre_eval_gui.py"

alias Gf="antoniovandre_funcoesgerador"

alias Gr="antoniovandre_graficocartesiano"

alias Grp="antoniovandre_graficocartesiano_parametrico"

alias Grpol="antoniovandre_graficocartesiano_polar"

alias Grppol="antoniovandre_graficocartesiano_parametricopolar"

alias Gr3="antoniovandre_graficocartesiano_3d"

alias Gr3sp="antoniovandre_graficocartesiano_3d_superficieparametrica"

alias Gr3spop="antoniovandre_graficocartesiano_3d_superficiepolar"

alias Gr3ct="antoniovandre_graficocartesiano_3d_curvatridimensional"

# Fim aliases matemáticos 1/1.

# Início aliases temporários 1/1.

alias aliastemp="evince /home/antoniovandre/livros\ \(antoniovandre-notebook\ specific\)/BACKUPED2/Cálculo\ I/cursoCalculoI-livro-a4-V2-2.pdf"

# Fim aliases temporários 1/1.

fi
