#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script para editar arquivos de texto, separado para ter privilégios dentro do sistema.

# Última atualização: 22-03-2020.

gedit $@

