#!/bin/sh

# Script de retomada do daemon "dropbox". De Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 09-03-2016.

dropbox start

sleep 3s

