#!/bin/sh

# Script de inicialização do player mps-youtube (mpsyt), por Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 08-10-2016.

cpulimit -l 5 -- xterm mpsyt

#nice -n 10 mpsyt

#sleep 5s

#for pid in $(ps -A | grep mpsyt | awk '{print $1}'); do renice 10 $pid; done
