#!/bin/bash

# Projeto Mathematical Ramblings.

# Script de executar programas em background

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 10-04-2020.

$@ &>> /dev/null &

