#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script de gravação de uma janela. Requer "recordmydesktop".

# Última atualização: 15-06-2024.

if ! hash recordmydesktop; then echo -e "${AV_VERMELHO}Software \"\" não encontrado${AV_SEMCOR}."; fi

recordmydesktop --windowid `xwininfo -display :0 | grep 'id: 0x' | grep -Eo '0x[a-z0-9]+'`
