#!/bin/sh

# Script de retomada do daemon "dropbox" em GUI. De Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 09-03-2016.

xterm antoniovandre_dropboxstart

