#!/bin/sh

# Script de cpulimit para Firefox. De Antonio Vandré Pedrosa Furtunato Gomes (http://bit.ly/antoniovandre_legadoontologico).

# Última atualização: 15-05-2017.

ARQUIVO_CPULIMIT_PORCENTAGEM="/home/antoniovandre/antoniovandre_cpulimit_porcentagem.txt"

if cpulimit -b -l $(cat "$ARQUIVO_CPULIMIT_PORCENTAGEM") -p `ps -A | grep firefox | awk '{print $1}'` 1>> /dev/null 2>> /dev/null; then echo "Sucesso."; read key; else echo "Erro. Pressione RETURN para sair."; read key; exit 1; fi

