#!/bin/bash

# Script de startup do script antoniovandre_megamount, de Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 02-08-2017.

sudo -u antoniovandre /home/antoniovandre/shell_scripts/Shell\ scripts\ -\ Ubuntu/antoniovandre_megamount
