#!/bin/sh

# Script de retomada da sincronização do diretório "dot_mozilla_Linux" no Dropbox. De Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 10-03-2016.

dropbox exclude exclude /home/antoniovandre/Dropbox/dot_mozilla_Linux/

sleep 3s

