#!/bin/sh

# Script de upload das imagens de mulheres reunidas no diretório único. Executar este script quando novas fotos forem adicionadas ao diretório. Leia "antoniovandre-notas_imagens_mulheres_(unique_directory).txt". De Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 11-10-2016.

for i in `seq 1 10`; do

megacopy -u a.vandre.g.cinco@gmail.com -p 1245780mg5 -l /mnt/sda2/imagens\ mulheres\ \(unique\ directory\) -r /Root/imagens\ mulheres\ \(unique\ directory\)

while ! ping -c 1 www.mega.nz; do sleep 5m; done

done
