#!/bin/sh

# Script de backup (cópia para o diretório cloud dropbox) dos shell scripts do Mythbuntu, para Antonio Vandré Pedrosa Furtunato Gomes (google.com/profiles/a.vandre.g).

# Última atualização: 24-07-2015.

cp -u /home/mythbuntu/Shell\ scripts/* /home/mythbuntu/Dropbox/Mythbuntu\ -\ Shell\ scripts/
