#!/bin/bash

# Script de inicialização do emulador de Playstation 2 PCSX2, de Antonio Vandré.

# Última atualização: 22-06-2025.

SETTINGSFILE="/home/antoniovandre/.var/app/net.pcsx2.PCSX2/config/PCSX2/inis/PCSX2.ini"

VALUE=$(find /run 2>> /dev/null | grep "PCSX2" | grep "PSX2 BIOS" | head -n 1 | sed 's/by\-app\/net\.pcsx2\.PCSX2\///g')

sed -i "/Bios =*/c\Bios = ${VALUE/\//\\\/}" "${SETTINGSFILE}"

flatpak run net.pcsx2.PCSX2
