#!/bin/bash

# Proprietário: Antonio Vandre Pedrosa Furtunato Gomes.

# Script de inicialização do Antonio Vandre's Image Viewer.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 14-03-2026. Não considerando alterações em variáveis globais.

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/shell_scripts/Util/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "${BASHSCRIPTSDIR}antoniovandre_cores_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n $TEMPDIR ]; then echo -e "${AV_VERMELHO}Diretório ramdisk não configurado${AV_SEMCOR}."; exit 1; fi

if ! hash iconv &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"iconv\" não encontrado${AV_SEMCOR}."; exit 1; fi

if [ "${#}" -lt "1" ]; then echo -e "${AV_VERMELHO}Erro ao encontrar o arquivo${AV_SEMCOR}."; exit 1; else

OLDDIR=$PWD;

IFS=$'\n'

LIST=""
TOTALCONTADOR="0"

for FILE in `ls -1 "${1%/*}/"*.{png,jpg,jpeg,bmp} 2>> /dev/null`; do TOTALCONTADOR=$(expr "${TOTALCONTADOR}" + "1"); FILE=$(echo -n "${FILE}"); if [ "${TOTALCONTADOR}" == "1" ]; then LIST="${FILE}"; else LIST="${LIST}|${FILE}"; fi; done

CONTADOR="1"

while [ $(echo -n "${LIST}" | cut -d "|" -f "${CONTADOR}") != "${1}" ]; do CONTADOR=$(expr "${CONTADOR}" + "1"); done

while true; do

FILE=$(echo -n "${LIST}" | cut -d "|" -f "${CONTADOR}")
DESTFILE=$(echo -n "${FILE##*/}" | iconv -t ASCII//TRANSLIT)
DESTFILE="${DESTFILE:0:10}..."

cp "${FILE}" "${TEMPDIR}${DESTFILE}"

cd "${TEMPDIR}"

/usr/bin/env QT_QPA_PLATFORM="xcb" /usr/local/bin/antoniovandre_imageviewer "${DESTFILE}"

EXITCODE=$?

FLAG="0"

if [ "${EXITCODE}" == "246" ]; then FLAG="1"; if [ "${CONTADOR}" -lt "${TOTALCONTADOR}" ]; then CONTADOR=$(expr "${CONTADOR}" + 1); else CONTADOR="1"; fi; else if [ "${CONTADOR}" -gt "1" ]; then CONTADOR=$(expr "${CONTADOR}" - 1); else CONTADOR="${TOTALCONTADOR}"; fi; fi

if [ "${EXITCODE}" == "245" ]; then FLAG="1"; if [ "${CONTADOR}" -gt "1" ]; then CONTADOR=$(expr "${CONTADOR}" - 1); else CONTADOR="${TOTALCONTADOR}"; fi; else if [ "${CONTADOR}" -lt "${TOTALCONTADOR}" ]; then CONTADOR=$(expr "${CONTADOR}" + 1); else CONTADOR="1"; fi; fi

rm "${DESTFILE}"

cd "${OLDDIR}"

if [ "${FLAG}" == "0" ]; then break; fi

done

fi
