#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).

# Script de log de inicializações de processos, de Antonio Vandré.

# Requer "dbxcli-linux-amd64".

# Última atualização: 21-02-2025.

NUMEROREGISTROS="1000"

if [ "${1}" == "" ]; then echo "Requer o argumento identificador do processo."; exit 1; fi

CABECALHO="Proprietário: Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).\n\nOs últimos ${NUMEROREGISTROS} registros do processo ${1}.\n\n"

ARQUIVOLOGINS="${HOME}/ramdisk/${1}.txt"

rm "${ARQUIVOLOGINS}" &>> /dev/null

if hash antoniovandre_verificarinternet_1 && antoniovandre_verificarinternet_1 &>> /dev/null; then

if hash dbxcli-linux-amd64 &>> /dev/null; then

dbxcli-linux-amd64 get "/Legado ontológico/Software logs/${ARQUIVOLOGINS##*/}" "${ARQUIVOLOGINS}" &>> /dev/null

if ls "${ARQUIVOLOGINS}" &>> /dev/null; then tail -n "$(($(cat ${ARQUIVOLOGINS} | wc -l) - $(echo -e "${CABECALHO}" | wc -l)))" "${ARQUIVOLOGINS}" > "${ARQUIVOLOGINS}.tmp"; tail -n "$((${NUMEROREGISTROS} - 1))" "${ARQUIVOLOGINS}.tmp" > "${ARQUIVOLOGINS}"; echo -e "${CABECALHO}" > "${ARQUIVOLOGINS}.tmp"; cat "${ARQUIVOLOGINS}" >> "${ARQUIVOLOGINS}.tmp"; mv "${ARQUIVOLOGINS}.tmp" "${ARQUIVOLOGINS}"; else echo -e "${CABECALHO}" > "${ARQUIVOLOGINS}"; fi

hostname | tr -d "\n" >> "${ARQUIVOLOGINS}"; echo -n ", " >> "${ARQUIVOLOGINS}"; date >> "${ARQUIVOLOGINS}"

dbxcli-linux-amd64 put "${ARQUIVOLOGINS}" "/Legado ontológico/Software logs/${ARQUIVOLOGINS##*/}" &>> /dev/null

dbxcli-linux-amd64 put "${ARQUIVOLOGINS}" "/Documents/BACKUPED14/Software logs/${ARQUIVOLOGINS##*/}" &>> /dev/null

fi
fi
