#!/bin/sh

# Script de retomada do daemon "dropbox" em GUI. De Antonio Vandré Pedrosa Furtunato Gomes (http://bit.ly/antoniovandre_legadoontologico).

# Última atualização: 09-03-2016.

xterm antoniovandre_dropboxstart

