#!/bin/sh

# Script de inicialização do cliente de e-mail Thunderbird, por Antonio Vandré Pedrosa Furtunato Gomes (http://antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 28-09-2016.

#cpulimit -l 15 thunderbird &

nice -n 0 thunderbird

#sleep 5s

#for pid in $(ps -A | grep thunderbird | awk '{print $1}'); do renice 10 $pid; done

