#!/bin/bash

# Script de backup do AV3DSpaceCatch - Estatísticas.txt, de Antonio Vandré.

# Última atualização: 19-10-2025.

#____________________

if ! hash git &>> /dev/null; then echo "Software \"git\" não encontrado."; exit 1; fi

if ! hash dbxcli-linux-amd64 &>> /dev/null; then echo "Software \"dbxcli-linux-amd64\" não encontrado."; exit 1; fi

DIR=$PWD; cd "/home/antoniovandre/GitHub/"; rm -fr "antoniovandre2/" &>> /dev/null

git clone --depth 1 "https://github.com/antoniovandre2/antoniovandre2"

cp "/home/antoniovandre/Documentos/AV3DSpaceCatch - Estatísticas.txt" "/home/antoniovandre/GitHub/antoniovandre2/"

cd "/home/antoniovandre/GitHub/antoniovandre2/"

git add "AV3DSpaceCatch - Estatísticas.txt" && git commit -m "Atualizando AV3DSpaceCatch - Estatísticas.txt" && git push

cd "${DIR}"

dbxcli-linux-amd64 put "/home/antoniovandre/Documentos/AV3DSpaceCatch - Estatísticas.txt" "/Documents/AV3DSpaceCatch - Estatísticas.txt"
