#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).

# Script para fill square em imagens.

# Dependências: ImageMagick, bc.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 29-03-2026. Não considerando alterações em variáveis globais.

if ! [ -n "$AVENV" ] &>> /dev/null; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/shell_scripts/Util/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$AVCORES" ] &>> /dev/null &>> /dev/null; then echo -ne "Carregando antoniovandre_cores... "; if ! source "antoniovandre_cores" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! hash bc &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"bc\" não encontrado${AV_SEMCOR}."; exit 1; fi

if ! hash magick &>> /dev/null; then if ! hash convert &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"ImageMagick\" não encontrado${AV_SEMCOR}."; exit 1; else EXECUTAVEL="convert"; fi; else EXECUTAVEL="magick"; fi

if [ "${#}" -lt "1" ]; then echo "Use \"antoniovandre_fillsquareimage <ARQUIVOIMAGEM>\"."; exit 1; fi

if ! [ -n "{TEMPDIR}" ] &>> /dev/null; then TEMPDIR="/tmp/"; fi

echo -n "Preenchendo \"${1}\"... "

FLAG="0";

TEMPFILE="${TEMPDIR}antoniovandre_fillsquareimage.png"

if ! cp "${1}" $(echo -n "${TEMPFILE}" | sed 's/%s/\_/g') &>> /dev/null; then FLAG="1"; fi

WIDTH=$(identify "${TEMPFILE}" | awk '{print $3}' | cut -d "x" -f 1)
HEIGHT=$(identify "${TEMPFILE}" | awk '{print $3}' | cut -d "x" -f 2)

if [ "${FLAG}" == "0" ]; then if ! "${EXECUTAVEL}" "${1}" -bordercolor white -border 2 "${TEMPFILE}" &>> /dev/null; then FLAG="1"; fi; fi

if [ "${WIDTH}" -gt "${HEIGHT}" ] &>> /dev/null; then if [ "${FLAG}" == "0" ]; then if ! "${EXECUTAVEL}" "${TEMPFILE}" -bordercolor black -border 2x$(echo "(${WIDTH} - ${HEIGHT}) / 2 + 2" | bc | tr -d "\n") "${1%.*} - fillsquare.${1##*.}" &>> /dev/null; then FLAG="1"; fi; fi; else if [ "${FLAG}" == "0" ]; then if ! "${EXECUTAVEL}" "${TEMPFILE}" -bordercolor black -border $(echo "(${HEIGHT} - ${WIDTH}) / 2 + 2" | bc | tr -d "\n")x2 "${1%.*} - fillsquare.${1##*.}" &>> /dev/null; then FLAG="1"; fi; fi; fi

if [ "${FLAG}" == "0" ]; then if ! rm "${TEMPFILE}" &>> /dev/null; then FLAG="1"; fi; fi

if [ "${FLAG}" == "0" ]; then echo -e "${AV_VERDE}Sucesso${AV_SEMCOR}."; else echo -e "${AV_VERMELHO}Ocorreu um erro${AV_SEMCOR}."; exit 1; fi
