#!/bin/sh

# Script de conexão em redes wifi utilizando o Network Manager, de Antonio Vandré Pedrosa Furtunato Gomes (http://antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 21-12-2016.

nmcli dev wifi con "$1" password "$2"
