#!/bin/bash

# Script de criptografar e descriptografar arquivos. De Antonio Vandré Pedrosa Furtunato Gomes.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 15-06-2024. Não considerando alterações em variáveis globais.

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/shell_scripts/Utilitários/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

INDEXFILE="${HOME}/antoniovandre-cryptindex.txt"
TEMPINDEXFILE="${TEMPDIR}avctif"
TEMPFILE="${TEMPDIR}avctf"

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "${BASHSCRIPTSDIR}antoniovandre_cores_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! hash ccrypt &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"ccrypt\" não encontrado${AV_SEMCOR}."; exit 1; fi

if [ "${1}" != "e" ] && [ "${1}" != "d" ]; then echo -e "${AV_VERMELHO}O argumento deve ser \"e\" para encrypt ou \"d\" para decrypt${AV_SEMCOR}."; exit 1; fi

if ! ls "${INDEXFILE}" &>> /dev/null; then echo -e "${AV_VERMELHO}Arquivo de índice não encontrado${AV_SEMCOR}."; exit 1; fi

# OLDIFS="${IFS}"
# IFS=","

case "${1}" in "e") echo -ne "Criptografando arquivos";; "d") echo -ne "Descriptografando arquivos";; esac

cat "${INDEXFILE}" > "${TEMPINDEXFILE}"

echo "" >> "${TEMPINDEXFILE}"

FLAG="0"

CONTADOR2="0"

while read LINHA; do TEMPLINHA=$(echo -n "${LINHA}" | awk 'BEGIN{FS=" "} {print $1}'
); if [ "${TEMPLINHA}" != "" ] && [ "${TEMPLINHA:0:1}" != "#" ]; then CONTADOR2=$(expr "${CONTADOR2}" + 1); CONTADOR="0"; for CAMPO in ${LINHA//,/ }; do CONTADOR=$(expr "${CONTADOR}" + 1); case "${CONTADOR}" in "1") SOURCE=$CAMPO;; "2") DEST=$CAMPO;; "3") SENHA=$CAMPO;; esac; done; case "${1}" in "e") if [ "${FLAG}" == "0" ]; then if ! cp "${SOURCE}" "${TEMPFILE}" &>> /dev/null; then FLAG="1"; fi; fi; if [ "${FLAG}" == "0" ]; then if ! ccrypt -e -K "${SENHA}" "${TEMPFILE}" &>> /dev/null; then FLAG="1"; fi; fi; if [ "${FLAG}" == "0" ]; then if ! mv "${TEMPFILE}.cpt" "${DEST}" &>> /dev/null; then FLAG="1"; fi; fi;; "d") if [ "${FLAG}" == "0" ]; then if ! cp "${DEST}" "${TEMPFILE}" &>> /dev/null; then FLAG="1"; fi; fi; if [ "${FLAG}" == "0" ]; then if ! ccrypt -d -K "${SENHA}" "${TEMPFILE}" &>> /dev/null; then FLAG="1"; fi; fi; if [ "${FLAG}" == "0" ]; then if ! mv "${TEMPFILE}" "${SOURCE}" &>> /dev/null; then FLAG="1"; fi; fi;; esac; echo -ne "."; fi; done < "${TEMPINDEXFILE}"

# IFS="${OLDIFS}"

rm "${TEMPINDEXFILE}"

if [ "${CONTADOR2}" == "0" ]; then echo -e "... Arquivo index vazio."; else if [ "${FLAG}" == "0" ]; then echo -e " ${AV_VERDE}Sucesso${AV_SEMCOR}."; else echo -e " ${AV_VERMELHO}Ocorreu um erro${AV_SEMCOR}."; exit 1; fi; fi

