#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script de carregamento de variáveis de ambiente.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 26-04-2026. Não considerando alterações em variáveis globais.

export AVENV="1"

export TEMPDIR="${HOME}/antoniovandre_temp/"

export AVSOFTWARESDIR="${HOME}/software_sources/"

export SCRIPTSDIR="${HOME}/shell_scripts/"

export BASHSCRIPTSDIR="${SCRIPTSDIR}Util/"

export BASHSCRIPTSDBXCLIDIR="${SCRIPTSDIR}dbxcli/"

export BASHSCRIPTSMATHDIR="${SCRIPTSDIR}AV C Math/"

export BASHSCRIPTSAV3DNAVIGATORDIR="${SCRIPTSDIR}AV3DNavigator/"

export CSOURCESDIR="${AVSOFTWARESDIR}C/"

export PATH="${PATH}:${AVSOFTWARESDIR}:${SCRIPTSDIR}:${BASHSCRIPTSDIR}:${BASHSCRIPTSDBXCLIDIR}:${BASHSCRIPTSMATHDIR}:${BASHSCRIPTSAV3DNAVIGATORDIR}:${CSOURCESDIR}:${CSOURCESDIR}Math"
