#!/bin/bash

# Proprietário: Antonio Vandre Pedrosa Furtunato Gomes.

# Script de inicialização do Antonio Vandre's Image Viewer.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 14-03-2026. Não considerando alterações em variáveis globais.

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/shell_scripts/Util/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "${BASHSCRIPTSDIR}antoniovandre_cores_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n $TEMPDIR ]; then echo -e "${AV_VERMELHO}Diretório ramdisk não configurado${AV_SEMCOR}."; exit 1; fi

if ! hash iconv &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"iconv\" não encontrado${AV_SEMCOR}."; exit 1; fi

FILE=$(echo "${1##*/}" | iconv -t ASCII//TRANSLIT)
FILE="${FILE:0:10}..."

cp "${1}" "${TEMPDIR}${FILE}"

if [ "${#}" -lt "1" ]; then echo -e "${AV_VERMELHO}Erro ao encontrar o arquivo${AV_SEMCOR}."; exit 1; else OLDDIR=$PWD; cd "${TEMPDIR}"; /usr/bin/env QT_QPA_PLATFORM="xcb" /usr/local/bin/antoniovandre_imageviewer "${FILE}"; rm "${FILE}"; cd "${OLDDIR}"; fi
