#!/bin/sh

# Script de contagem de caracteres, de Antonio Vandré Pedrosa Furtunato Gomes (http://antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 11-11-2016.

echo -n "$1" | wc -c
