#!/bin/sh

# Script de liberação de uso total do processador, através do cpulimit para Firefox. De Antonio Vandré Pedrosa Furtunato Gomes (http://antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 08-10-2016.

if cpulimit -b -l 100 -p `ps -A | grep firefox | awk '{print $1}'` 1>> /dev/null 2>> /dev/null; then echo "Sucesso."; read key; else echo "Erro."; read key; exit 1; fi
