#!/bin/sh

# Script de limitação do uso da cpu pelo Chromium, na GUI. De Antonio Vandré Pedrosa Furtunato Gomes (http://antoniovandre.github.io/MathematicalRamblingsjs).

xterm antoniovandre_cpulimit_chromium

