#!/bin/sh

# Script de liberação do uso da cpu pelo Chromium, na GUI. De Antonio Vandré Pedrosa Furtunato Gomes (http://bit.ly/antoniovandre_legadoontologico).

xterm antoniovandre_cpulimit_chromium_free

