#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes (http://antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 10-07-2024. Não considerando alterações em variáveis/parâmetros globais.

# __________

# Gerando logs.

"${HOME}/shell_scripts/Util/antoniovandre_logprocessos" "Inicialização Linux"

"${HOME}/shell_scripts/Util/antoniovandre_capturaprocessos" &

# Ajustando gamma e saturação.

if hash xcalib &>> /dev/null; then if [ "$(ps -A | grep Xorg)" != "" ]; then xcalib -c &>> /dev/null && xcalib -gc 1 -b 0 -co 99 -a &>> /dev/null; fi; fi

if hash "${HOME}/libvibrant-1.1.1/build/cli/vibrant-cli" &>> /dev/null; then "${HOME}/libvibrant-1.1.1/build/cli/vibrant-cli" $(xrandr | grep " connected" | cut -d " " -f 1) 1.5; fi

# __________
