#!/bin/bash

# Script de busca de vídeos pornográficos por nome contido. De Antonio Vandré Pedrosa Furtunato Gomes.

# última atualização: 20-02-2025.

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/shell_scripts/Utilitários/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "${BASHSCRIPTS}antoniovandre_cores" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! hash mpv; then echo -e "${AV_VERMELHO}Software \"mpv\" não encontrado${AV_SEMCOR}."; exit 1; fi

DIRETORIOS="/home/antoniovandre/871b1058-973a-4ece-be68-eba0d5b3a519/Vídeos/xxx/|/home/antoniovandre/abd4b09a-d330-4a01-a4fd-21c793f1b043/Antonio Vandré Pedrosa Furtunato Gomes/Vídeos/xxx/|/home/antoniovandre/C0D0970BD0970736/Antonio Vandré Pedrosa Furtunato Gomes/Vídeos/xxx/|/home/antoniovandre/Google Drive/xxx videos (GD specific)/xxx2/"

IFS='|'

for CAMINHO in `echo -n "${DIRETORIOS}"`; do if [ "${1}" == "play" ]; then mpv --no-audio "${CAMINHO}"*"${2}"* 2>> /dev/null; else echo -ne "${AV_CIANOCLARO}"; ls "${CAMINHO}"*"${1}"* 2>> /dev/null; echo -ne "${AV_SEMCOR}"; fi; done
