#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).

# Script de sincronização de arquivos entre uma pasta local e outra no Dropbox.

# Dependências: dbxcli.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 21-03-2026. Não considerando alterações em variáveis globais.

if ! [ -n "$AVENV" ] &>> /dev/null; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/shell_scripts/Util/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$AVCORES" ] &>> /dev/null &>> /dev/null; then echo -ne "Carregando antoniovandre_cores... "; if ! source "antoniovandre_cores" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

EXECUTAVEL="dbxcli-linux-arm"

if ! hash "${EXECUTAVEL}" &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"${EXECUTAVEL}\" não encontrado${AV_SEMCOR}."; exit 1; fi

FOLDER="${HOME}/dbxclisync"
OLDDIR=$PWD

echo -n "Sincronizando"

FLAG="0"
IFS=$'\n'

mkdir "${FOLDER}" &>> /dev/null
cd "${FOLDER}"

if [ "${1}" == "get" ] &>> /dev/null; then for FILE in `"${EXECUTAVEL}" ls /dbxclisync/ 2>> /dev/null`; do if ! "${EXECUTAVEL}" get $(echo -n "${FILE#*/}" | xargs) &>> /dev/null; then FLAG="1"; fi; echo -n "."; if [ "${FLAG}" == "1" ] &>> /dev/null; then break; fi; done; fi

if [ "${1}" == "put" ] &>> /dev/null; then cd "${FOLDER}"; for FILE in `ls -1 *`; do if ! "${EXECUTAVEL}" put "${FILE}" "/dbxclisync/${FILE}" &>> /dev/null; then FLAG="1"; fi; echo -n "."; if [ "${FLAG}" == "1" ] &>> /dev/null; then break; fi; done; fi

cd "${OLDDIR}"

if [ "${FLAG}" == "0" ] &>> /dev/null; then echo -e " ${AV_VERDE}Sucesso${AV_SEMCOR}."; else echo -e " ${AV_VERMELHO}Ocorreu um erro${AV_SEMCOR}."; fi
