#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script inicializador do Chromium com uso limitado da CPU.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 02-07-2020.

if ! hash chromium-browser &>> /dev/null; then echo "\"chromium-browser\" não encontrado."; exit 1; fi

if ! hash antoniovandre_cpulimit &>> /dev/null; then echo "\"antoniovandre_cpulimit\" não encontrado."; exit 1; fi

if ! hash antoniovandre_background &>> /dev/null; then echo "\"antoniovandre_background\" não encontrado."; exit 1; fi

antoniovandre_background chromium-browser; sleep 5s

echo "Cpulimit. Varrendo o padrão \"chromium\"..."

antoniovandre_cpulimit chromium p

