#!/bin/sh

# Script de inicialização do gedit com arquivos secretos, de Antonio Vandré Pedrosa Furtunato Gomes.

# Última atualização: 29-09-2016.

cpulimit -l 10 -- gedit --new-window /home/antoniovandre/Documentos/antoniovandre-anotacoes_privadas.txt /home/antoniovandre/Dropbox/Documents/BACKUPED14/antoniovandre-notas_xxx_videos.txt /home/antoniovandre/Dropbox/Documents/BACKUPED14/OBSERVAÇÕES\ IMPORTANTES.txt /home/antoniovandre/Dropbox/volatile\ docs/antoniovandre-tarefas_pendentes.txt /home/antoniovandre/Dropbox/Documents/BACKUPED14/antoniovandre-notas_imagens_mulheres_\(unique_directory\).txt

#nice -n 10 gedit --new-window /home/antoniovandre/Documentos/antoniovandre-anotacoes_privadas.txt /home/antoniovandre/Dropbox/Documents/BACKUPED14/antoniovandre-notas_xxx_videos.txt /home/antoniovandre/Dropbox/Documents/BACKUPED14/OBSERVAÇÕES\ IMPORTANTES.txt /home/antoniovandre/Dropbox/volatile\ docs/antoniovandre-tarefas_pendentes.txt /home/antoniovandre/Dropbox/Documents/BACKUPED14/antoniovandre-notas_imagens_mulheres_\(unique_directory\).txt
