#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).

# Script para reiniciar o roteador.

# Dependências: curl.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 26-03-2026. Não considerando alterações em variáveis globais.

if ! [ -n "$AVENV" ] &>> /dev/null; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/shell_scripts/Util/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$AVCORES" ] &>> /dev/null &>> /dev/null; then echo -ne "Carregando antoniovandre_cores... "; if ! source "antoniovandre_cores" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! hash curl &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"curl\" não encontrado${AV_SEMCOR}."; exit 1; fi

ARQUIVOSENHA="${HOME}/senharoteador.txt"
ARQUIVOROUTERIP="${HOME}/iproteador.txt"

IP=$(cat "${ARQUIVOROUTERIP}" | tr -d "\n")

echo -n "Reiniciando ${IP} ..."; if curl --user "admin:$(cat ${ARQUIVOSENHA} | tr -d '\n')" "http://${IP}/userRpm/SysRebootRpm.htm?Reboot=Reboot" &>> /dev/null; then echo -e " ${AV_VERDE}Sucesso${AV_SEMCOR}."; else echo -e " ${AV_VERMELHO}Ocorreu um erro${AV_SEMCOR}."; exit 1; fi
