#!/bin/bash

# Script de backup do Mathematical Ramblings quiz data.txt, de Antonio Vandré.

# Última atualização: 21-03-2025.

#____________________

if ! hash git &>> /dev/null; then echo "Software \"git\" não encontrado."; exit 1; fi

DIR=$PWD; cd "/home/antoniovandre/GitHub/"; rm -fr "antoniovandre2/" &>> /dev/null

git clone --depth 1 "https://github.com/antoniovandre2/antoniovandre2"

cp "/home/antoniovandre/Documentos/Mathematical Ramblings quiz data.txt" "/home/antoniovandre/GitHub/antoniovandre2/"

cd "/home/antoniovandre/GitHub/antoniovandre2/"

git add "Mathematical Ramblings quiz data.txt" && git commit -m "Atualizando Mathematical Ramblings quiz data.txt" && git push

cd "${DIR}"
