#!/bin/bash

# Script de backup das anotações públicas, de Antonio Vandré.

# Última atualização: 21-03-2025.

#____________________

if ! hash git &>> /dev/null; then echo "Software \"git\" não encontrado."; exit 1; fi

DIR=$PWD; cd "/home/antoniovandre/GitHub/"; rm -fr "antoniovandre2/" &>> /dev/null

git clone --depth 1 "https://github.com/antoniovandre2/antoniovandre2"

cp "/home/antoniovandre/Documentos/antoniovandre-anotações_públicas-5.txt" "/home/antoniovandre/GitHub/antoniovandre2/"

cd "/home/antoniovandre/GitHub/antoniovandre2/"

git add "antoniovandre-anotações_públicas-5.txt" && git commit -m "Atualizando antoniovandre-anotações_públicas-5.txt" && git push

cd "${DIR}"
