#!/bin/bash

# Script de verificação de dispositivos na rede local, por Antonio Vandré Pedrosa Furtunato Gomes (http://antoniovandre.github.io/MathematicalRamblingsjs).

# Dependências: ping.

# Última atualização: 26-03-2026.

if ! [ -n "$AVENV" ] &>> /dev/null; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/shell_scripts/Util/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$AVCORES" ] &>> /dev/null &>> /dev/null; then echo -ne "Carregando antoniovandre_cores... "; if ! source "antoniovandre_cores" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! hash ping &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"ping\" não encontrado${AV_SEMCOR}."; exit 1; fi

if [ "${#}" != "2" ]; then echo -e "Entre com \"antoniovandre_verificacaodispositivosredelocal <MIN> <MAX>\"${AV_SEMCOR}."; exit 1; fi

if (! [[ "${1}" =~ ^[0-9]*$ ]]) || (! [[ "${1}" =~ ^[0-9]*$ ]]); then echo -e "${AV_VERMELHO}Os parâmetros devem ser inteiros não negativos${AV_SEMCOR}."; exit 1; fi

if [ "${1}" -gt "${2}" ]; then echo -e "${AV_VERMELHO}O primeiro parâmetro deve ser menor ou igual ao segundo${AV_SEMCOR}."; exit 1; fi

ARQUIVOROUTERIP="${HOME}/iproteador.txt"
ARQUIVOIPIGNORE="${HOME}/ipignorar.txt"

IP=$(cat "${ARQUIVOROUTERIP}" | tr -d "\n")

echo -e "Pressione \"q\" para sair.\n"

SAIDAVOLUNTARIA="0"

IFS=$'\n'

for ip in `seq "${1}" "${2}"`; do read -rsn1 -t 0.1 input; if [ "${input}" == "q" ]; then SAIDAVOLUNTARIA="1"; echo ""; break; fi; echo -ne "\r${ip} / ${2} "; if ping -c 1 "${IP%.*}.${ip}" &>> /dev/null; then FLAG=0; for i in `cat "${ARQUIVOIPIGNORE}"`; do if [ "${i}" == "${IP%.*}.${ip}" ]; then FLAG="1"; break; fi; done; if [ "${FLAG}" == "0" ]; then echo -e "${AV_VERDE}${IP%.*}.${ip}${AV_SEMCOR}"; fi; fi; done

if [ "${SAIDAVOLUNTARIA}" == "0" ]; then echo ""; fi
