#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).

# Simples script de caixa de diálogo.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 21-03-2026. Não considerando alterações em variáveis globais.

if [ "${#}" -lt "2" ]; then echo "Requer no mínimo 2 argumentos."; exit 1; fi

if [ "${1}" != "python" ] && [ "${1}" != "gtk" ] && [ "${1}" != "ncurses" ] && [ "${1}" != "console" ] && [ "${1}" != "java" ]; then echo "O segundo argumento deve ser \"python\" ou \"gtk\" ou \"ncurses\" ou \"console\" ou \"java\"."; exit 1; fi

if [ "${1}" == "python" ]; then
	if ! hash python3 &>> /dev/null; then echo "Python 3 não instalado."; exit 1; fi

	if ! ls "${HOME}/software_sources/Python/Aviso.py" &>> /dev/null; then echo "Script Python não encontrado."; exit 1; fi

	python3 "${HOME}/software_sources/Python/Aviso.py" "${2}"
else if [ "${1}" == "gtk" ]; then
	if ! hash "aviso" &>> /dev/null; then echo "Software GTK não encontrado."; exit 1; fi

	if [ "${#}" != "3" ]; then echo "Requer no mínimo 3 argumentos."; exit 1; fi

	if ! [[ "${3}" =~ ^[0-9]+$ ]] || [ "${3}" -lt "1" ]; then echo "O terceiro argumento deve ser um númer inteiro positivo."; exit 1; fi

	"aviso" "${2}" "${3}"
else if [ "${1}" == "ncurses" ]; then
	if ! hash "aviso_ncurses" &>> /dev/null; then echo "Software ncurses não encontrado."; exit 1; fi

	xterm -e "aviso_ncurses" "${2}"
else if [ "${1}" == "console" ]; then
	if ! ls "${HOME}/shell_scripts/Util/antoniovandre_dialogbox" &>> /dev/null; then echo "Software console não encontrado."; exit 1; fi

	"${HOME}/shell_scripts/Util/antoniovandre_dialogbox" "${2}"
else if [ "${1}" == "java" ]; then
	if ! hash java &>> /dev/null; then echo "Java não instalado."; exit 1; fi

	if ! ls "${HOME}/software_sources/Java/AntonioVandreDialogBox.java" &>> /dev/null; then echo "Software Java não encontrado."; exit 1; fi

	java "${HOME}/software_sources/Java/AntonioVandreDialogBox.java" "${@:2:$#}"
fi; fi; fi; fi; fi
