#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script de inicialização do AV3DSpaceWar.

# Última atualização: 24-07-2024. Não considerando alterações em variáveis globais e comentários.

DIRETORIO="${HOME}/software_sources/Java/AV3DSpaceWar/"

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/shell_scripts/Utilitários/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

# "${BASHSCRIPTSDIR}antoniovandre_backupav3dspacewar"

cd "${DIRETORIO}"

# PIDSOLD=$(ps -u antoniovandre | grep java)

java -jar AV3DSpaceWarLauncher.jar "${HOME}/Documentos/AV3DSpaceWar - Estatísticas.txt"

# sleep 10s

# PIDSNEW=$(ps -u antoniovandre | grep java)

# IFS=$'\n'

# FLAG="0"; for ITEM in `echo -n ${PIDSNEW}`; do for ITEM2 in `echo -n ${PIDSOLD}`; do if [ "${ITEM}" == "${ITEM2}" ]; then FLAG="1"; fi; done; if [ "${FLAG}" == "0" ]; then PID=$(echo -n "${ITEM}" | awk '{print $1}'); break; fi; done

# OLD=$(cat "${HOME}/Documentos/AV3DSpaceWar - Estatísticas.txt" | tr -d '\n')

# while [ "$(ps -u antoniovandre | grep $PID | awk '{print $1}')" == "${PID}" ]; do sleep 30s; NEW=$(cat "${HOME}/Documentos/AV3DSpaceWar - Estatísticas.txt" | tr -d '\n'); if [ "${OLD}" != "${NEW}" ]; then OLD=$NEW; "${BASHSCRIPTSDIR}antoniovandre_backupav3dspacewar"; fi; done
