#!/bin/sh

# Script de liberação do uso da cpu pelo Firefox, na GUI. De Antonio Vandré Pedrosa Furtunato Gomes (http://antoniovandre.github.io/MathematicalRamblingsjs).

xterm antoniovandre_cpulimit_firefox_free

