#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script para mostrar os aliases.

# Última atualização: 16-06-2024.

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/shell_scripts/Util/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

ALIASESSCRIPT="${BASHSCRIPTSDIR}antoniovandre_aliases"

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "${BASHSCRIPTS}antoniovandre_cores" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

while read -r LINHA; do if [ "${LINHA:0:6}" == "alias " ]; then TAMANHO=$(expr $(echo -n "${LINHA}" | wc -c) - 5); echo -e "${AV_CIANOCLARO}alias${AV_SEMCOR}${LINHA:5:$TAMANHO}\n"; fi; done < "${ALIASESSCRIPT}"

exit 0
