#!/bin/sh

# Script de cpulimit para Chromium. De Antonio Vandré Pedrosa Furtunato Gomes (http://bit.ly/antoniovandre_legadoontologico).

# Última atualização: 20-10-2016.

ARQUIVO_CPULIMIT_PORCENTAGEM="/home/antoniovandre/Dropbox/antoniovandre_cpulimit_software/antoniovandre_cpulimit_porcentagem.txt"

killall cpulimit 2>> /dev/null

for pid in `ps -A | grep chromium | awk '{print $1}'`; do if ! cpulimit -b -l $(cat "$ARQUIVO_CPULIMIT_PORCENTAGEM") -p $pid 1>> /dev/null 2>> /dev/null; then echo "Erro. Pessione RETURN para sair."; read key; exit 1; fi; done

echo "Sucesso."

read key

