#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes (antoniovandre.github.io/MathematicalRamblingsjs).

# Script de conversão de um arquivo gif para mp4.

# Use "antoniovandre_giftomp4 <ARQUIVOGIF> <NUMEROREPETICOES>".

# Dependências: ffmpeg.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 25-04-2026. Não considerando alterações em variáveis globais.

if ! [ -n "$AVENV" ] &>> /dev/null; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/shell_scripts/Util/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$AVCORES" ] &>> /dev/null &>> /dev/null; then echo -ne "Carregando antoniovandre_cores... "; if ! source "antoniovandre_cores" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! hash ffmpeg &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"ffmpeg\" não encontrado${AV_SEMCOR}."; exit 1; fi

if [ "${#}" != 2 ]; then echo "Use \"antoniovandre_giftomp4 <ARQUIVOGIF> <NUMEROREPETICOES>\"."; exit 1; fi

if [ "${1##*.}" != "gif" ]; then echo "Entre com um arquivo gif."; exit 1; fi

if ! [[ "${2}" =~ ^[0-9]+$ ]]; then echo "O número de repetições deve ser um inteiro positivo."; exit 1; fi

ffmpeg -stream_loop "${2}" -i "${1}" -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" "${1%.*}.mp4"
