#!/bin/bash

# Script de atualizaçãodo sistem Linux. De Antonio Vandré Pedrosa Furtunato Gomes (http://bit.ly/antoniovandre_legadoontologico).

# Última atualização: 03-05-2025.

sudo bash -c "if hash apt-get; then apt-get update && apt-get upgrade -y && apt-get autoremove -y && apt-get clean; fi; if hash flatpak; then flatpak update -y; fi; if hash snap; then snap refresh; fi"

if ! [ -z $1 ]; then if [ $1 == "prompt" ]; then echo -e "\nPressione RETURN para sair."; read; fi; fi
