#!/bin/sh

# Script de retomada da sincronização do diretório "dot_mozilla_Linux" no Dropbox, em GUI. De Antonio Vandré Pedrosa Furtunato Gomes (http://bit.ly/antoniovandre_legadoontologico).

# Última atualização: 10-03-2016.

xterm antoniovandre_syncdotmozilla_dropbox

