#!/bin/sh

# Última atualização: 22-09-2017.

for i in `seq 1 10`; do

megacopy -r /Root/BACKUPED177 -l /home/antoniovandre/Vídeos/xxxvideossecondfolder/BACKUPED177 -u a.vandre.g.dezoito@gmail.com -p 1245780mg18

while ! ping -c 1 www.mega.nz; do sleep 5m; done

done

/home/antoniovandre/shell_scripts/Shell\ scripts\ -\ Ubuntu/antoniovandre_build_xxxvideolist_from_mega
