#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes [google.com/profiles/a.vandre.g].

echo "Init:"

date

echo ""

$1 $2 $3 $4 $5 $6 $7 $8 $9

echo ""

echo "End:"

date

echo $'_____\n'
