#!/bin/sh

# Script de verificação do estado de atualização do LODB em GUI. De Antonio Vandré Pedrosa Furtunato Gomes (http://bit.ly/antoniovandre_legadoontologico).

# Última atualização: 09-03-2016.

xterm antoniovandre_estadoatualizacao_lodb

