#!/bin/sh

# Script para execução do "antoniovandre_backup_legadoontologico_ext" em interface gráfica. De Antonio Vandré Pedrosa Furtunato Gomes (http://antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 08-03-2016.

xterm antoniovandre_backup_legadoontologico_ext

