#!/bin/sh

# Script de criptografia dos arquivos secrecretos na interface X, de Antonio Vandré Pedrosa Furtunato Gomes (http://antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 29-11-2016.

xterm antoniovandre_criptografar_arquivos_secretos
