#!/bin/sh

# Script de verificação do estado de atualização do LODB. De Antonio Vandré Pedrosa Furtunato Gomes (http://bit.ly/antoniovandre_legadoontologico).

# Última atualização: 09-03-2016.

dropbox filestatus /home/antoniovandre/Dropbox/Legado\ ontológico/

echo "Pressione RETURN para sair."

read key
