#!/bin/bash

# Proprietário: Antonio Vandre Pedrosa Furtunato Gomes.

# Script de inicialização do Antonio Vandre's Image Viewer.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 15-03-2026. Não considerando alterações em variáveis globais.

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/shell_scripts/Util/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "${BASHSCRIPTSDIR}antoniovandre_cores_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n $TEMPDIR ]; then TENPDIR="/tmp/"; fi

if ! hash iconv &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"iconv\" não encontrado${AV_SEMCOR}."; exit 1; fi

if ! hash zenity &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"zenity\" não encontrado${AV_SEMCOR}."; exit 1; fi

if [ "${#}" == "0" ]; then ARG=$(zenity --file-selection 2>> /dev/null); else ARG="${1}"; fi

if [ "${ARG}" == "" ]; then exit 0; fi

OLDDIR=$PWD;

IFS=$'\n'

LIST=""
TOTALCONTADOR="0"

for FILE in `ls -1 "${ARG%/*}/"*.{png,PNG,jpg,JPG,jpeg,JPEG,bmp,BMP,dib,DIB,jpe,JPE,jp2,JP2,pbm,PBM,pgm,PGM,ppm,PPM,sr,SR,ras,RAS,tiff,TIFF,tif,TIFF} 2>> /dev/null`; do TOTALCONTADOR=$(expr "${TOTALCONTADOR}" + "1"); FILE=$(echo -n "${FILE}"); if [ "${TOTALCONTADOR}" == "1" ]; then LIST="${FILE}"; else LIST="${LIST}|${FILE}"; fi; done

CONTADOR="1"

while [ $(echo -n "${LIST}" | cut -d "|" -f "${CONTADOR}") != "${ARG}" ]; do CONTADOR=$(expr "${CONTADOR}" + "1"); if [ "${CONTADOR}" -gt "${TOTALCONTADOR}" ]; then echo -e "${AV_VERMELHO}Arquivo não suportado${AV_SEMCOR}."; exit 1; fi; done

while true; do

FILE=$(echo -n "${LIST}" | cut -d "|" -f "${CONTADOR}")
DESTFILE=$(echo -n "${FILE##*/}" | iconv -t ASCII//TRANSLIT)
DESTFILE="${DESTFILE:0:10}..."

cp "${FILE}" "${TEMPDIR}${DESTFILE}"

cd "${TEMPDIR}"

RESULT=$(/usr/bin/env QT_QPA_PLATFORM="xcb" /home/antoniovandre/software_sources/C++/Image/antoniovandre_imageviewer "${DESTFILE}" 2>> /dev/null)

EXITCODE=$?

if [ "${RESULTADO}" == "Erro ao carregar a imagem." ]; then echo "${RESULTADO}"; exit 1; fi

FLAG="0"

if [ "${EXITCODE}" == "246" ]; then FLAG="1"; if [ "${CONTADOR}" -lt "${TOTALCONTADOR}" ]; then CONTADOR=$(expr "${CONTADOR}" + 1); else CONTADOR="1"; fi; fi

if [ "${EXITCODE}" == "245" ]; then FLAG="1"; if [ "${CONTADOR}" -gt "1" ]; then CONTADOR=$(expr "${CONTADOR}" - 1); else CONTADOR="${TOTALCONTADOR}"; fi; fi

rm "${DESTFILE}"

cd "${OLDDIR}"

if [ "${FLAG}" == "0" ]; then break; fi

done
