#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes (http://bit.ly/antoniovandre_legadoontologico).

# Script gerador do gráfico do histórico de uso das funções em "Antonio Vandré Pedrosa Furtunato Gomes - Maxima API".

# Última atualização: 21-03-2020.

if ! hash antoniovandre_echo 1>> /dev/null 2>> /dev/null; then echo "antoniovandre_echo não encontrado."; read; exit 1; fi

if ! [ -n "$executou_prescript" ]; then antoniovandre_echo -n "Executando prescript... "; if ! source antoniovandre_bash_maxima_prescript; then echo -e "${AV_VERMELHO}Falhou${AV_SEMCOR}."; exit 1; else echo -e "${AV_VERDE}OK${AV_SEMCOR}."; fi; fi

c1="0"

c2="0"

echo -n "" > "$avmhgpdf"

echo -n "" > "$avmhgpdf_t"

while read -r linha_history_1; do if [ "$linha_history_1" != "" ]; then while read -r linha_history_2; do if [ "$linha_history_2" != "" ]; then comando_1="$(echo ${linha_history_1} | cut -d'"' -f 2 | cut -d',' -f 1)"; comando_2="$(echo $linha_history_2 | cut -d'"' -f 2 | cut -d',' -f 1)"; if [ "$comando_1" == "$comando_2" ]; then c2="$(expr "$c2" + 1)"; fi; fi; done < "$avmh"; fi; c3="0"; while read -r linha_t; do if [ "$comando_1" == "$linha_t" ]; then c3="1"; fi; done < "$avmhgpdf_t"; if [ "$c3" == "0" ] && [ ! "$comando_1" == "" ]; then echo "${c1} ${comando_1//"_"/"\\\_"} ${c2}" >> "$avmhgpdf"; c1="$(expr "$c1" + 1)"; echo "$comando_1" >> "$avmhgpdf_t"; fi; c2="0"; done < "$avmh"

gnuplot -p -e "set xtics font 'Verdana,6'; set yrange [0:]; set boxwidth 0.3; set style fill solid; set xtics 1; set ytics 1; set terminal png size 800,600; set output '${avmhgpi##*/}'; set xtics rotate by 45 right; plot '${avmhgpdf}' using 1:3:xtic(2) notitle with boxes linecolor rgb '#444444'" 1>> /dev/null 2>> /dev/null

mv "${avmhgpi##*/}" "$avmhgpi" 1>> /dev/null 2>>/dev/null

rm "$avmhgpdf_t" 1>> /dev/null 2>> /dev/null

