#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script de visualização de estatísticas de uso do AV3DNavigator, não Termux, de Antonio Vandré.

# Última atualização: 15-08-2025.

echo -ne "Carregando antoniovandre_cores... "; if ! source "${BASHSCRIPTS}antoniovandre_cores_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi

TEMPDATFILE="${TEMPDIR}av3dst.dat"
PLOTPNGFILE="${TEMPDIR}av3dst.png"
AV3DSTBACKGROUND="/home/antoniovandre/shell_scripts/AV3DNavigator/AV3DNavigator - Estatísticas background.png"

if ! hash curl &>> /dev/null; then echo -ne "${AV_VERMELHO}Software \"curl\" não encontrado${AV_SEMCOR}"; echo "."; exit 1; fi

echo -ne "Fetching data..."; RAW=$(curl -s "https://api.github.com/repos/antoniovandre/AV3DNavigatorStats/releases" 2>> /dev/null); RAWAUTH=$(curl -s https://raw.githubusercontent.com/antoniovandre/AV3DNavigatorStats/refs/heads/main/AV3DNavigatorAuthorStats.txt 2>> /dev/null); if ([ "${RAW}" != "" ] && [ $(echo -n "${RAWAUTH}" | sed "1p;d") == "AV3DNavigatorAuthorStats" ]); then echo -e " ${AV_VERDE}Ok${AV_SEMCOR}."; else echo -e " ${AV_VERMELHO} Ocorreu um erro${AV_SEMCOR}."; exit 1; fi

DATA=$(date)

NAMES=$(echo -n "${RAW}" | sed 's/AV3DNavigatorStats//g' | grep "\"name\": \"AV3DNavigator" | awk '{print $2}' | tr -d ',')

NAMESAUTH=$(TN=$(echo "${RAWAUTH}" | wc -l); for N in `seq -s " " 2 "${TN}"`; do BUFF=$(echo -n "${RAWAUTH}" | sed "${N}p;d"); if ([ "${BUFF:0:1}" != "" ] && [ "${BUFF:0:1}" != "#" ]); then BUFF2=$(echo -n "${BUFF}" | cut -f "1" -d "," | tr -d " "); if [ "${N}" -lt "${TN}" ]; then echo -n "\"${BUFF2}\" "; else echo -n "\"${BUFF2}\""; fi; fi; done)

VALUES=$(echo -n "${RAW}" | grep "download_count" | awk '{print $2}' | tr -d ',')

VALUESAUTH=$(TN=$(echo "${RAWAUTH}" | wc -l); for N in `seq -s " " 2 "${TN}"`; do BUFF=$(echo -n "${RAWAUTH}" | sed "${N}p;d"); if ([ "${BUFF:0:1}" != "" ] && [ "${BUFF:0:1}" != "#" ]); then BUFF2=$(echo -n "${BUFF}" | cut -f "2" -d "," | tr -d " "); if [ "${N}" -lt "${TN}" ]; then echo -n "${BUFF2} "; else echo -n "${BUFF2}"; fi; fi; done)

CONTADOR=$(echo -n $VALUES | wc -w)

CONTADORAUTH=$(echo -n $VALUESAUTH | wc -w)

echo -e "Estatísticas de uso do AV3DNavigator:\n"

echo -n "" > "${TEMPDATFILE}"

MAX="0"

for ID in `seq -s " " 1 "${CONTADOR}"`; do echo -ne "Chave: "; CHAVE=$(echo -n "${NAMES}" | sed "${ID}q;d" | tr -d '\n'); echo -n "${CHAVE}"; echo -n "${ID} ${CHAVE}" >> "${TEMPDATFILE}"; echo -ne ". "; VALORDEBT="0"; for IDAUTH in `seq -s " " 1 "${CONTADORAUTH}"`; do CHAVEAUTH=$(echo -n "${NAMESAUTH}" | sed "${IDAUTH}q;d" | tr -d '\n'); if [ "${CHAVE}" == "${CHAVEAUTH}" ]; then VALORDEBT=$(echo -n "${VALUESAUTH}" | sed "${IDAUTH}q;d" | tr -d '\n'); break; fi; done; echo -ne "Valor: ${AV_CIANOCLARO}"; VALOR=$(expr $(echo -n "${VALUES}" | sed "${ID}q;d" | tr -d '\n') - "${VALORDEBT}"); if [[ "${MAX}" -lt "${VALOR}" ]]; then MAX=$VALOR; fi; echo -n "${VALOR}"; echo -ne " ${VALOR}\n" >> "${TEMPDATFILE}"; echo -e "${AV_SEMCOR}."; done

if [ "${ID}" == "0" ]; then

echo -e "1 \"No data\" 0\n2 \"No data\" 0\n3 \"No data\" 0\n4 \"No data\" 0\n5 \"No data\" 0\n6 \"No data\" 0" > "${TEMPDATFILE}"

MAXY="4"

MAXYTITULO="2.5"
MAXYTITULOT="3"
MAXYTITULOB="1"

gnuplot -e "set boxwidth 0.5; set style fill solid; set term png; set terminal png size 800,600; set output \"${PLOTPNGFILE}\"; set multiplot; set border 0; set lmargin 0; set rmargin 0; set bmargin 0; set tmargin 0; unset tics; unset title; plot '${AV3DSTBACKGROUND}' binary filetype=png w rgbimage; set border 1; set lmargin 4; set rmargin 4; set bmargin 12; set tmargin 2; set tics; set xtics rotate by 55 right font 'Verdana,9'; set yrange [0:${MAXY}]; set obj rect from 1,${MAXYTITULOB} to 4,${MAXYTITULOT} fillcolor rgb 'white'; set label \"AV3DNavigator - Estatísticas de uso - ${DATA}.\n\nAinda sem dados coletados.\" at 1.1,${MAXYTITULO} font 'Verdana,14'; plot \"${TEMPDATFILE}\" using 1:3:xtic(2) with boxes linecolor rgb \"blue\" notitle; unset multiplot;" &>> /dev/null

else if [[ "${MAX}" -le "3" ]]; then

MAXY="7"

MAXYTITULO="5"
MAXYTITULOT="6"
MAXYTITULOB="4"

else

MAXY=$(echo "${MAX} * 1.5" | bc | sed "s/\..*//")

MAXYTITULO=$(echo "${MAX} * 1.3" | bc | sed "s/\..*//")
MAXYTITULOT=$(echo "${MAX} * 1.4" | bc | sed "s/\..*//")
MAXYTITULOB=$(echo "${MAX} * 1.2" | bc | sed "s/\..*//")

fi

gnuplot -e "set boxwidth 0.5; set style fill solid; set term png; set terminal png size 800,600; set output \"${PLOTPNGFILE}\"; set multiplot; set border 0; set lmargin 0; set rmargin 0; set bmargin 0; set tmargin 0; unset tics; unset title; plot '${AV3DSTBACKGROUND}' binary filetype=png w rgbimage; set border 1; set lmargin 4; set rmargin 4; set bmargin 12; set tmargin 2; set tics; set xtics rotate by 55 right font 'Verdana,9'; set yrange [0:${MAXY}]; set obj rect from 1,${MAXYTITULOB} to ${ID},${MAXYTITULOT} fillcolor rgb 'white'; set label \"AV3DNavigator - Estatísticas de uso - ${DATA}.\" at 1.1,${MAXYTITULO} font 'Verdana,14'; plot \"${TEMPDATFILE}\" using 1:3:xtic(2) with boxes linecolor rgb \"blue\" notitle, '' using 1:3:3 with labels offset 0,1 notitle; unset multiplot;" &>> /dev/null

fi

eog "${PLOTPNGFILE}" &>> /dev/null
