#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script de escrita com delay, sem som, para Android.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 27-07-2021. Não considerando alterações em variáveis globais.

DELAY="0"

VAR="${1}"
TAMANHO=${#VAR}
CONTADOR="0"

while [ $CONTADOR -lt $TAMANHO ]; do CHAR=${VAR:$CONTADOR:1}; if [ -z $CHAR ]; then echo -n " "; else GLOBIGNORE="*" echo -n "${CHAR}"; fi; sleep ${DELAY}s; CONTADOR=$(expr $CONTADOR + 1); done

if [ -z "${2}" ]; then echo ""; else if ! [ "${2}" == "n" ]; then echo ""; fi; fi

