#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script de mostrar frases aleatórias, para Android.

# Última atualização: 07-06-2024. Não considerando alterações em variáveis globais.

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/storage/shared/av_softwares/BASH scripts/antoniovandre_env_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando cores... "; if ! source "${BASHSCRIPTSDIR}antoniovandre_cores_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! ls "${BASHSCRIPTSDIR}antoniovandre_echo_android" 1>> /dev/null 2>> /dev/null; then echo -e "${AV_VERMELHO}antoniovandre_echo_android não encontrado${AV_SEMCOR}."; fi

ARQUIVOFRASES="/data/data/com.termux/files/home/storage/shared/av_docs/antoniovandre-frases.txt"

TOTALLINHAS=$(cat "${ARQUIVOFRASES}" | wc -l)

LINHA=$(expr $(expr $(date +%s) % $TOTALLINHAS) + 1)

LINHA="${LINHA}p"

FRASE=$(sed -n "${LINHA}" < "${ARQUIVOFRASES}")

echo -ne "${AV_CIANOCLARO}"; bash "${BASHSCRIPTSDIR}antoniovandre_echo_android" "${FRASE}"; echo -ne "${AV_SEMCOR}"

if ! [ -z $1 ]; then if [ $1 == "prompt" ]; then echo -e "\nPressione RETURN para sair."; read; fi; fi

