#!/bin/bash

# Script voltado para evitar a desativação das contas MEGA por inatividade, tocando em cada uma delas fazendo login e executando apenas o comando megals, do 3rd party Megatools, para Android. De Antonio Vandré Pedrosa Furtunato Gomes.

# Última atualização: 07-06-2024. Não considerando alterações em variáveis globais.

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/storage/shared/av_softwares/BASH scripts/antoniovandre_env_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "${BASHSCRIPTSDIR}antoniovandre_cores_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! hash megals &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"megals\" não encontrado${AV_SEMCOR}."; exit 1; fi

ARQUIVODADOS="/data/data/com.termux/files/home/storage/shared/antoniovandremegadados_android.txt"

if ! ls "${ARQUIVODADOS}" &>> /dev/null; then echo -e "${AV_VERMELHO}Arquivo de dados não encontrado${AV_SEMCOR}."; exit 1; fi

while read LINHA; do if [ "${LINHA:0:1}" != "#" ] && [ "${LINHA:0:1}" != "" ]; then EMAIL="$(echo ${LINHA} | cut -d ',' -f 1)"; SENHA="$(echo ${LINHA} | cut -d ',' -f 2)"; echo -n "Tocando \"${EMAIL}\"... "; if megals -u "${EMAIL}" -p "${SENHA}" &>> /dev/null; then echo -e "${AV_VERDE}OK${AV_SEMCOR}."; else echo -e "${AV_VERMELHO}Falhou${AV_SEMCOR}."; fi; fi; done < ${ARQUIVODADOS}

