#!/bin/bash

# Script de criptografia, para Android, Termux shortcut. De Antonio Vandré Pedrosa Furtunato Gomes.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 09-06-2024.

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/storage/shared/av_softwares/BASH scripts/antoniovandre_env_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

bash "${BASHSCRIPTSDIR}antoniovandre_cripto_android" e

read
