#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script de aliases, para Android. Deve ser executado com "source".

# Última atualização: 10-08-2024. Não considerando alterações em variáveis globais.

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/storage/shared/av_softwares/BASH scripts/antoniovandre_env_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "${BASHSCRIPTSDIR}antoniovandre_cores_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if [ "${1}" == "0" ]; then

echo -ne "Removendo aliases... "

unalias apbk

unalias av3dst

unalias f

unalias s

unalias ha

unalias hd

unalias h

unalias hmrac

unalias e

unalias mg

unalias mgne

unalias mgoe

unalias ave

unalias mxg

unalias mxh

unalias log

unalias loz

unalias mrc

unalias vint

unalias rnl

unalias crpt

unalias tmega

unalias md5d

unalias sa

unalias ra

unalias rss

unalias uol

unalias scdly

unalias folha

unalias mruqd

# Início aliases matemáticos 1/2.

unalias S
unalias P
unalias Im
unalias Se
unalias Co
unalias Ta
unalias Ct
unalias Sc
unalias Cs
unalias As
unalias Ac
unalias At
unalias Act
unalias Asc
unalias Acs
unalias Pt
unalias Rts
unalias Vnp
unalias Ev
unalias Evn
unalias Der
unalias Int
unalias Fmp
unalias Pc
unalias Rz
unalias Dt

unalias Nr

unalias Pts

unalias Ce

unalias Re

unalias Gp

unalias Comp

unalias Gf

unalias Gr

unalias Grp

unalias Grpol

unalias Grppol

unalias Gr3

unalias Gr3sp

unalias Gr3spol

unalias Gr3ct

# Fim aliases matemáticos 1/2.

# Início aliases matemáticos 2/2.

unalias EvJ

unalias marca

# Fim aliases matemáticos 2/2.

echo -e "${AV_VERDE}Ok${AV_SEMCOR}."

else

echo -ne "Carregando aliases... "

alias apbk="dbxcli-linux-arm get \"/Legado ontológico/antoniovandre-anotações_públicas-5.txt\" \"${HOME}/storage/shared/av_docs/antoniovandre-anotações_públicas-5.txt\"; dbxcli-linux-arm put \"${HOME}/storage/shared/av_docs/antoniovandre-anotações_públicas-5.txt\" \"/Documents/BACKUPED14/antoniovandre-anotações_públicas-5.txt\""

alias av3dst="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_av3dnavigator_estatisticas_android"

alias f="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_frases_aleatorias_android"

alias s="cd $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')"

alias ha="cd ${HOME}/storage/shared/"

alias hd="cd ${HOME}/storage/downloads/"

alias h="cd ${HOME}/"

alias hmrac="cd ${HOME}/storage/downloads/Mathematical\ Ramblings\ -\ Artes\ cartesianas"

alias e="exit"

alias mg="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_mathgame"

alias mgne="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_mathgame ne"

alias mgoe="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_mathgame oe"

alias ave="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_echo_android"

alias mxg="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_maxima_history_gnuplot_generator_android"

alias mxh="cd ${HOME}/storage/shared/av_maxima/"

alias log="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_logenerator_android"

alias loz="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_lozipgenerator_android"

alias mrc="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_mathematicalramblings_check_android"

alias vint="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_verificarinternet_android"

alias rnl="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_renomearlote_android"

alias crpt="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_cripto_android"

alias tmega="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_touchmega_android"

alias md5d="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_md5dir_android"

alias sa="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_showaliases_android"

alias ra="source $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_aliases_android 0"

alias rss="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_leitorrss_android"

alias uol="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_leitorrss_android http://rss.uol.com.br/feed/noticias.xml 120"

alias scdly="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_leitorrss_android https://www.sciencedaily.com/rss/all.xml 120"

alias folha="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_leitorrss_android https://feeds.folha.uol.com.br/emcimadahora/rss091.xml 120"

alias mruqd="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_unificarmathematicalramblingsquizdata_android"

# Início aliases matemáticos 1/2.

alias S="antoniovandre_soma_android"
alias P="antoniovandre_produto_android"
alias Im="antoniovandre_inversomultiplicativo_android"
alias Se="antoniovandre_seno_android"
alias Co="antoniovandre_cosseno_android"
alias Ta="antoniovandre_tangente_android"
alias Ct="antoniovandre_cotangente_android"
alias Sc="antoniovandre_secante_android"
alias Cs="antoniovandre_cossecante_android"
alias As="antoniovandre_arcoseno_android"
alias Ac="antoniovandre_arcocosseno_android"
alias At="antoniovandre_arcotangente_android"
alias Act="antoniovandre_arcocotangente_android"
alias Asc="antoniovandre_arcosecante_android"
alias Acs="antoniovandre_arcocossecante_android"
alias Pt="antoniovandre_potencia_android"
alias Rts="antoniovandre_reduzirtermossemelhantes_android"
alias Vnp="antoniovandre_valornumericopolinomio_android"
alias Ev="antoniovandre_eval_android"
alias Evn="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_eval_android_nolog"
alias Der="antoniovandre_derivada_android"
alias Int="antoniovandre_integraldefinida_android"
alias Fmp="antoniovandre_funcaomaisproxima_android ${HOME}/storage/shared/av_softwares/C/Math/antoniovandre_pontos.txt ${HOME}/storage/shared/av_softwares/C/Math/antoniovandre_funcoes.txt 1"
alias Pc="antoniovandre_produtocomplexos_android"
alias Rz="antoniovandre_raizesfuncao_android"
alias Dt="antoniovandre_determinante_android"

alias Nr="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_numeroraizes_android"

alias Pts="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_proximotermosequencia_android"

alias Ce="if ls ${HOME}/storage/shared/av_softwares/C/Math/antoniovandre_math_estatisticas_android.txt &>> /dev/null; then cat ${HOME}/storage/shared/av_softwares/C/Math/antoniovandre_math_estatisticas_android.txt; else echo \"Arquivo de estatísticas matemáticas ainda não existente.\"; fi"

alias Re="rm ${HOME}/storage/shared/av_softwares/C/Math/antoniovandre_math_estatisticas_android.txt &>> /dev/null; rm ${HOME}/storage/shared/av_softwares/C/Math/antoniovandre_math_estatisticas_android.png &>> /dev/null; ls &>> /dev/null"

alias Gp="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_gnuplot_mathstatistics_android"

alias Comp="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_cmath_compilar_android"

alias Gf="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_funcoesgerador_android"

alias Gr="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_graficocartesiano_android"

alias Grpol="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_graficocartesiano_polar_android"

alias Grp="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_graficocartesiano_parametrico_android"

alias Grppol="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_graficocartesiano_parametricopolar_android"

alias Gr3="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_graficocartesiano_3d_android"

alias Gr3sp="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_graficocartesiano_3d_superficieparametrica_android"

alias Gr3spol="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_graficocartesiano_3d_superficiepolar_android"

alias Gr3ct="bash $(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_graficocartesiano_3d_curvatridimensional_android"

# Fim aliases matemáticos 1/2.

# Início aliases matemáticos 2/2.

alias EvJ="java -jar ${HOME}/storage/shared/av_softwares/JavaAntonioVandreEval/JavaAntonioVandreEval.jar"

alias marca="bash mathematicalramblings_convgifmp4"

# Fim aliases matemáticos 2/2.

echo -e "${AV_VERDE}Ok${AV_SEMCOR}."

fi
