#!/bin/sh

# Script de verificação de conexão com a internet, apenas um toque, para Android. De Antonio Vandré Pedrosa Furtunato Gomes (http://antoniovandre.github.io/MathematicalRamblingsjs).

# Última atualização: 07-06-2024. Não considerando alterações em variáveis globais.

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/storage/shared/av_softwares/BASH scripts/antoniovandre_env_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

URLFILE="${BASHSCRIPTSDIR}antoniovandre_urltouch.txt"

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "${BASHSCRIPTSDIR}antoniovandre_cores_android" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

URLTOUCH=$(cat "${URLFILE}" | tr -d "\n")

if ! hash tracepath &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"tracepath\" não encontrado${AV_SEMCOR}."; exit 1; fi

if ! ls "${URLFILE}" &>> /dev/null; then echo -e "${AV_VERMELHO}Arquivo de URL não encontrado${AV_SEMCOR}."; exit 1; else URLTOUCH=$(cat "${URLFILE}" | tr -d "\n"); fi

if tracepath -m 1 "${URLTOUCH}" &>> /dev/null; then echo -e "${AV_VERDE}Internet acessível${AV_SEMCOR}."; else echo -e "${AV_VERMELHO}Sem internet${AV_SEMCOR}."; exit 1; fi

