#!/bin/bash.exe

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script para mostrar os aliases. Para Cygwin.

# Última atualização: 14-07-2022.

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "${DIRETORIOTRABALHO}${DIRETORIOCYGWIN}antoniovandre_cores" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! [ -n "$ARQUIVOANOTACOES" ]; then echo -ne "Carregando definições de arquivos de anotações... "; if source /cygdrive/f/Antonio\ Vandré\ Pedrosa\ Furtunato\ Gomes/Cygwin/antoniovandre_arquivoarquivosanotacoes; then echo -e "${AV_VERDE}Sucesso${AV_SEMCOR}."; else echo -e "${AV_VERMELHO}Ocorreu um erro${AV_SEMCOR}."; FLAGRC="1"; fi; fi

ALIASESSCRIPT="${DIRETORIOTRABALHO}${DIRETORIOCYGWIN}antoniovandre_aliases"

while read -r LINHA; do if [ "${LINHA:0:6}" == "alias " ]; then TAMANHO=$(expr $(echo -n "${LINHA}" | wc -c) - 5); echo -e "${AV_CIANOCLARO}alias${AV_SEMCOR}${LINHA:5:$TAMANHO}\n"; fi; done < "${ALIASESSCRIPT}"

exit 0
