#!/bin/bash.exe

# Script de renomear arquivos em lote. De Antonio Vandré Pedrosa Furtunato Gomes. Para Cygwin.

# Licença: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 10-07-2021.

TARGETDIR="/home/antoniovandre/to rename/"

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "antoniovandre_cores" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if [ "${1}" == "" ]; then echo -e "${AV_VERMELHO}Argumento vazio${AV_SEMCOR}."; exit 1; fi

DIR="${PWD}"
if ! cd "${TARGETDIR}" &>> /dev/null; then echo -e "${AV_VERMELHO}Erro ao entrar no diretório de renomeação${AV_SEMCOR}."; exit 1; fi

OLDIFS="${IFS}"
IFS=$'\n'

echo -ne "Renomeando arquivos em lote"

CONTADOR="0";

for FILE in `ls -1 * 2>> /dev/null`; do echo -ne "."; CONTADOR=$(expr "${CONTADOR}" + 1); if ls "${1} - ${CONTADOR}.${FILE##*.}" &>> /dev/null; then STRDIF=" - antoniovandre"; else STRDIF=""; fi; if [ "${FILE##*.}" != "${FILE%%.*}" ]; then EXTENSAO=".${FILE##*.}"; else EXTENSAO=""; fi; if ls "${1} - ${CONTADOR}${STRDIF}${EXTENSAO}" &>> /dev/null; then echo -e " ${AV_VERMELHO}Conflito de nomes${AV_SEMCOR}."; exit 1; fi; if ! mv "${FILE}" "${1} - ${CONTADOR}${STRDIF}${EXTENSAO}" &>> /dev/null; then echo -e " ${AV_VERMELHO}Ocorreu uma falha${AV_SEMCOR}."; exit 1; fi; done

IFS="${OLDIFS}"

cd "${DIR}"

if [ "${CONTADOR}" != "0" ]; then echo -e " ${AV_VERDE}Sucesso${AV_SEMCOR} ao renomear todos os arquivos."; else echo -e ". ${AV_VERMELHO}Diretório vazio${AV_SEMCOR}."; fi

