#!/bin/bash.exe

# Script de verificação de conexão com a internet. De Antonio Vandré Pedrosa Furtunato Gomes (http://antoniovandre.github.io/MathematicalRamblingsjs). Para Cygwin.

# Última atualização: 17-07-2021.

URLFILE="/usr/local/share/antoniovandre_urltouch.txt"

if ! ls "${URLFILE}" &>> /dev/null; then echo -e "${AV_VERMELHO}Arquivo de URL não encontrado${AV_SEMCOR}."; exit 1; else URLTOUCH=$(cat "${URLFILE}" | tr -d "\n"); fi

if TRACERT.EXE -h 1 "${URLTOUCH}" &>> /dev/null; then echo -e "${AV_VERDE}Internet acessível${AV_SEMCOR}."; else echo "${AV_VERMELHO}Sem internet${AV_SEMCOR}."; exit 1; fi

