#!/bin/bash

# Script voltado para evitar a desativação das contas MEGA por inatividade, tocando em cada uma delas fazendo login e executando apenas o comando megals, do 3rd party Megatools, para Cygwin, usuário Guest. De Antonio Vandré Pedrosa Furtunato Gomes.

# Última atualização: 16-10-2022.

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "/home/Guest/antoniovandre_cores" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! hash megals &>> /dev/null; then echo -e "${AV_VERMELHO}Software \"megals\" não encontrado${AV_SEMCOR}."; exit 1; fi

ARQUIVODADOS="${DIRETORIOTRABALHO}antoniovandremegadados.txt"

if ! ls "${ARQUIVODADOS}" >> /dev/null; then echo -e "${AV_VERMELHO}Arquivo de dados não encontrado${AV_SEMCOR}."; exit 1; fi

if ! ls "${ARQUIVODADOS}" &>> /dev/null; then echo -e "${AV_VERMELHO}Arquivo de dados não encontrado${AV_SEMCOR}."; exit 1; fi

while read LINHA; do if [ "${LINHA:0:1}" != "#" ] && [ "${LINHA:0:1}" != "" ]; then EMAIL="$(echo ${LINHA} | cut -d ',' -f 1)"; SENHA="$(echo ${LINHA} | cut -d ',' -f 2)"; echo -n "Tocando \"${EMAIL}\"... "; if megals -u "${EMAIL}" -p "${SENHA}" &>> /dev/null; then echo -e "${AV_VERDE}OK${AV_SEMCOR}."; else echo -e "${AV_VERMELHO}Falhou${AV_SEMCOR}."; fi; fi; done < "${ARQUIVODADOS}"

