#!/bin/bash

# Proprietário: Antonio Vandré Pedrosa Furtunato Gomes.

# Script gerador de funções para uso de "antoniovandre_funcaomaisproxima" e "antoniovandre_funcaomaisproxima", de Antonio Vandré Pedrosa Furtunato Gomes.

# Várias opções devido às limitações do compilador/hardware.

# Licença de uso: Atribuição-NãoComercial-CompartilhaIgual (CC BY-NC-SA).

# Última atualização: 11-03-2026. Não considerando as alterações nas variáveis globais, comentação de linhas, e adaptações para continuidade quando houver crash.

if ! [ -n "$AVENV" ]; then echo -ne "Carregando variáveis de ambiente... "; if ! source "${HOME}/storage/shared/av_softwares/BASH scripts/antoniovandre_env" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

if ! hash antoniovandre_eval &>> /dev/null; then echo "${AV_VERMELHO}\"antoniovandre_eval\" não encontrado.${AV_SEMCOR}."; exit 1; fi

ARQUIVOFUNCOES="${HOME}/Temp/antoniovandre_funcoes.txt"

POTENCIA="1.2"
VALORMINIMO="-15000"
VALORMAXIMO="15000"
VALORPASSO="1"

VARIAVEL="X"

if ! [ -n "$AVCORES" ]; then echo -ne "Carregando antoniovandre_cores... "; if ! source "$(echo -n $BASHSCRIPTSDIR | sed 's/\ /\\\ /g')antoniovandre_cores" &>> /dev/null; then echo -e "Ocorreu um erro.\n"; else echo -e "${AV_VERDE}Ok${AV_SEMCOR}.\n"; fi; fi

echo -n "" > "${ARQUIVOFUNCOES}"

# Gerador de polinômios de grau zero.

for i in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done >> "${ARQUIVOFUNCOES}"

# Gerador de polinômios do primeiro grau.

for i in `seq $VALORMINIMO $VALORPASSO "-${VALORPASSO}" | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done >> "${ARQUIVOFUNCOES}"

for i in `seq $VALORPASSO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done >> "${ARQUIVOFUNCOES}"

# Gerador de polinômios do segundo grau.

for i in `seq $VALORMINIMO $VALORPASSO "-${VALORPASSO}" | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^2+($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done >> "${ARQUIVOFUNCOES}"

for i in `seq $VALORPASSO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^2+($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done >> "${ARQUIVOFUNCOES}"

# Gerador de polinômios do terceiro grau.

#for i in `seq $VALORMINIMO $VALORPASSO "-${VALORPASSO}" | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^3+($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^2+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

#for i in `seq $VALORPASSO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^3+($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^2+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

# Gerador de polinômios do quarto grau.

#for i in `seq $VALORMINIMO $VALORPASSO "-${VALORPASSO}" | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for m in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^4+($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^3+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^2+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+(${m}),"; done; done; done; done; done >> "${ARQUIVOFUNCOES}"

#for i in `seq $VALORPASSO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for m in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^4+($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^3+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^2+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+(${m}),"; done; done; done; done; done >> "${ARQUIVOFUNCOES}"

# Gerador de polinômios do quinto grau.

#for i in `seq $VALORMINIMO $VALORPASSO "-${VALORPASSO}" | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for m in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for n in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^5+($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^4+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^3+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^2+(${m})*${VARIAVEL}+(${n}),"; done; done; done; done; done; done >> "${ARQUIVOFUNCOES}"

#for i in `seq $VALORPASSO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for m in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for n in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^5+($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^4+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^3+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}^2+(${m})*${VARIAVEL}+(${n}),"; done; done; done; done; done; done >> "${ARQUIVOFUNCOES}"

# Gerador de funções senoidais.

#for i in `seq $VALORMINIMO $VALORPASSO "-${VALORPASSO}" | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*sen(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

#for i in `seq $VALORPASSO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*sen(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

# Gerador de funções cossenoidais.

for i in `seq $VALORMINIMO $VALORPASSO "-${VALORPASSO}" | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*cos(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

for i in `seq $VALORPASSO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*cos(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

# Gerador de funções tangenciais.

#for i in `seq $VALORMINIMO $VALORPASSO "-${VALORPASSO}" | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*tg(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

#for i in `seq $VALORPASSO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*tg(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

# Gerador de funções cotangenciais.

#for i in `seq $VALORMINIMO $VALORPASSO "-${VALORPASSO}" | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*cotg(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

#for i in `seq $VALORPASSO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*cotg(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

# Gerador de funções tipo secante.

#for i in `seq $VALORMINIMO $VALORPASSO "-${VALORPASSO}" | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*sec(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

#for i in `seq $VALORPASSO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*sec(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

# Gerador de funções tipo cossecante.

#for i in `seq $VALORMINIMO $VALORPASSO "-${VALORPASSO}" | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*cossec(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

#for i in `seq $VALORPASSO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*cossec(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

# Gerador de funções modulares tipo afim.

for i in `seq $VALORMINIMO $VALORPASSO "-${VALORPASSO}" | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*modulo(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

for i in `seq $VALORPASSO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))*modulo(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

# Gerador de funções tipo 1/x.

for i in `seq $VALORMINIMO $VALORPASSO "-${VALORPASSO}" | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))/(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

for i in `seq $VALORPASSO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for j in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for k in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do for l in `seq $VALORMINIMO $VALORPASSO $VALORMAXIMO | tr ',' '.'`; do echo -n "($(T=$(antoniovandre_eval "(${i}/modulo(${i}))piso((modulo(${i}))^${POTENCIA})" 0); echo -n "${T%.*}"))/(($(T=$(antoniovandre_eval "(${j}/modulo(${j}))piso((modulo(${j}))^${POTENCIA})" 0); echo -n "${T%.*}"))*${VARIAVEL}+($(T=$(antoniovandre_eval "(${k}/modulo(${k}))piso((modulo(${k}))^${POTENCIA})" 0); echo -n "${T%.*}")))+($(T=$(antoniovandre_eval "(${l}/modulo(${l}))piso((modulo(${l}))^${POTENCIA})" 0); echo -n "${T%.*}")),"; done; done; done; done >> "${ARQUIVOFUNCOES}"

if [ $(cat "${ARQUIVOFUNCOES}" | wc -c) != "0" ]; then sed -i '$ s/.$//' "${ARQUIVOFUNCOES}"; fi

echo -e "Arquivo \"${AV_AMARELO}${ARQUIVOFUNCOES}${AV_SEMCOR}\" construído."
